version: "3.5"
services:
  diva:
    image: diva.diva-holesky.public.dappnode.eth:0.2.5
    build:
      context: diva
      args:
        UPSTREAM_VERSION: v24.10.1
    restart: unless-stopped
    volumes:
      - diva-vol:/var/diva/
      - diva-log-vol:/var/log/divad/
    environment:
      DIVA_VAULT_PASSWORD: null
      DIVA_API_KEY: null
    ports:
      - "5050:5050"
    expose:
      - "9000"
      - "30000"
  validator:
    image: validator.diva-holesky.public.dappnode.eth:0.2.5
    build:
      context: validator
      args:
        UPSTREAM_VERSION: multiarch-v24.10.0
    restart: unless-stopped
  ui:
    image: ui.diva-holesky.public.dappnode.eth:0.2.5
    build:
      context: operator-ui
      args:
        UPSTREAM_VERSION: v24.10.1
    restart: unless-stopped
    expose:
      - "80"
  vector:
    image: vector.diva-holesky.public.dappnode.eth:0.2.5
    build:
      context: vector
      args:
        UPSTREAM_VERSION: nightly-2024-08-21-alpine
    restart: unless-stopped
    volumes:
      - diva-log-vol:/var/log/divad/
    environment:
      USERNAME: username-address
volumes:
  diva-vol: {}
  diva-log-vol: {}
