[sources.diva_logs]
type = "file"
include = ["/var/log/divad/*.log"]

[sinks.loki]
type = "loki"
inputs = ["diva_logs"]
endpoint = "https://1038435:glc_eyJvIjoiMTI2MjM1MyIsIm4iOiJzdGFjay0xMDgwNjU2LWludGVncmF0aW9uLWJldGE0IiwiayI6IkNCaUZ3OGgwNUlROGc4ME4zTDdlelY2OCIsIm0iOnsiciI6InByb2QtdXMtZWFzdC0wIn19@logs-prod-006.grafana.net"
labels = {app="diva", job="${USERNAME}"}
encoding.codec = "json"
